### PR TITLE
fix for /asyncquery returning different results than /query

### PR DESCRIPTION
**Pull request by saramsey**
WARNING!  Prior to December 14, do *NOT* merge this pull request into the `production` branch until we have permission from workflow owners and NCATS. (There is a merging procedure that involves updating git tags and such; see #1754 for a checklist). Thank you.

### CODE REVIEW

**Comment by saramsey** [comment]
This PR code is deployed into `http://arax-backup.rtx.ai/fork-test` which I can start up at your convenience, for testing.

**Comment by saramsey** [comment]
For demonstration that this patch fixes the issue, see the parent issue #1759.

**Review by amykglen — APPROVED** [review]
These changes look good to me! Thanks!

**Comment by saramsey** [comment]
credit for suggesting fix c91c66f goes to @amykglen

**Comment by saramsey** [comment]
Update, I have merged commit 691c66f into the `master` branch. We cannot merge into "production" until we have NCATS and workflow owners' permission.

**Review by edeutsch — APPROVED** [review]

**Pull request merged**
