### PR TITLE
#1171

### PR DESCRIPTION
**Pull request by kvarforl**
With these changes, here is an example of a node id and name for something annotated as human species:
[https://www.uniprot.org/uniprot/P0DJZ0](https://www.uniprot.org/uniprot/P0DJZ0)
```
UniProtKB:P0DJZ0        11K
```

And here is an example of a node id and name for a non human species:
[https://www.uniprot.org/uniprot/O57245](https://www.uniprot.org/uniprot/O57245)
```
UniProtKB:O57245        3-beta-HSD (Vaccinia virus (strain Ankara) (VACV))
```

The evidence codes from the names are now at the end of the description field, formatted  as "Evidence Codes from Name: {ev_codes} "

### CODE REVIEW

**Comment by kvarforl** [comment]
Note that I ended up using the `'OS'` entry of the record dict instead of the existing entries for `'organism'`, because I thought that was more in line with what Eric was requesting. I made this PR instead of just merging because I wanted to confirm with @saramsey that this doesn't cause issues before truly commiting to this fix :)

**Comment by saramsey** [comment]
Hi @kvarforl I think it would make sense to create a small test  input "dat" file and run it, and diff the output JSON with and without the proposed code change. Does that make sense?  You can paste the diff into the issue.

**Comment by kvarforl** [comment]
Okay, I created a tiny dat file `~/testuniprot.dat` on `kg2lindsey.rtx.ai`. It only contains three entries from the larger uniprot file, with the following ids:

- P0DJZ0 (human with no evidence codes, no change expected)
- O57245 (not human, no evidence codes, so expect change in name)
- P11198 (not human, includes evidence codes so expect changes in name and description) 

After running the following, the output is as expected :)
```
cd ~/kg2-code
git checkout master
python3 ~/kg2-code/uniprotkb_dat_to_json.py ~/testuniprot.dat output1171.json --test
git add output1171.json
git checkout issue1171
python3 ~/kg2-code/uniprotkb_dat_to_json.py ~/testuniprot.dat output1171.json --test
git diff output1171.json
```


I took the liberty of splicing out the center of the description field for the sake of posting in this issue: it was long enough to make the diff hard to read.
```diff
"full_name": "Steroid Delta-isomerase",
             "id": "UniProtKB:O57245",
             "iri": "https://identifiers.org/uniprot:O57245",
-            "name": "3-beta-HSD",
+            "name": "3-beta-HSD (Vaccinia virus (strain Ankara) (VACV))",
             "provided_by": "identifiers_org_registry:uniprot",
             "publications": [
                 "DOI:10.1006/viro.1998.9123",
@@ -219,11 +219,11 @@
             "category_label": "protein",
             "creation_date": "01-JUL-1989",
             "deprecated": false,
-            "description": "-!- FUNCTION: [Outer capsid protein VP4]: Spike-forming protein thatmediates virion attachment to the host epithelial ..... Copyrighted by the UniProt Consortium, see https://www.uniprot.org/termsDistributed under the Creative Commons Attribution (CC BY 4.0) License---------------------------------------------------------------------------",
+            "description": "-!- FUNCTION: [Outer capsid protein VP4]: Spike-forming protein thatmediates virion attachment to the host epithelial.... Copyrighted by the UniProt Consortium, see https://www.uniprot.org/termsDistributed under the Creative Commons Attribution (CC BY 4.0) License---------------------------------------------------------------------------Evidence Codes from Name: {ECO:0000255|HAMAP-Rule:MF_04132} ",
"full_name": "Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}",
             "id": "UniProtKB:P11198",
             "iri": "https://identifiers.org/uniprot:P11198",
-            "name": "Outer capsid protein VP5* {ECO:0000255|HAMAP-Rule:MF_04132}",
+            "name": "Outer capsid protein VP5* ",
             "provided_by": "identifiers_org_registry:uniprot",
             "publications": [
                 "DOI:10.1007/s10719-006-5435-y",
```

**Comment by saramsey** [comment]
Nice. Can you merge it, please?

**Pull request merged**
