### PR TITLE
Some update

### PR DESCRIPTION
**Pull request by chunyuma**
This PR conducts the following:

1. Merge the recent update on the ARAX's algorithm from [a closed PR ](https://github.com/RTXteam/RTX/pull/2335) that wasn't merged into the master branch.
2. Update the `code/config_dbs.json` to change the path location of new xDTD and xCRG database
3. Modify some tests for `test_ranker.py`

### CODE REVIEW

**Comment by dkoslicki** [comment]
Were the ranking results checked against the list from #2300? I.e. the comparison from [here](https://github.com/RTXteam/RTX/issues/2300#issuecomment-2220769049) showed the new ranker was doing pretty well. Are the ranker changes in this PR already included in that? If not, it would be prudent to at least spot-check the ranker (better yet, run it through the benchmark repo) given these changes.

**Comment by chunyuma** [comment]
@dkoslicki, the change in this ranker script is not significantly different from the one in #2300, but just includes [a looping algorithm](https://github.com/RTXteam/RTX/issues/2334#issuecomment-2269709844) proposed by Eric (see #2334). As I mentioned in Slack, it has passed [almost all ranker tests](https://github.com/RTXteam/RTX/blob/0f9ec6364e8288aa9775acad302d9a2ab3ce9b81/code/ARAX/test/test_ARAX_ranker.py#L86-L890) but only failed only on [test_ARAXRanker_test9_asset619](https://github.com/RTXteam/RTX/blob/0f9ec6364e8288aa9775acad302d9a2ab3ce9b81/code/ARAX/test/test_ARAX_ranker.py#L304), [test_ARAXRanker_test9_asset623](https://github.com/RTXteam/RTX/blob/0f9ec6364e8288aa9775acad302d9a2ab3ce9b81/code/ARAX/test/test_ARAX_ranker.py#L360), [test_ARAXRanker_test13_asset355](https://github.com/RTXteam/RTX/blob/0f9ec6364e8288aa9775acad302d9a2ab3ce9b81/code/ARAX/test/test_ARAX_ranker.py#L484). I have listed the reason there. I think it is sufficient to demonstrate its validity, right？

**Comment by chunyuma** [comment]
BTW, reason of those three failed tests are not due to the change in the algorithm. 

For [test_ARAXRanker_test13_asset355](https://github.com/RTXteam/RTX/blob/0f9ec6364e8288aa9775acad302d9a2ab3ce9b81/code/ARAX/test/test_ARAX_ranker.py#L484), it seems to be due to the change in Node Synonymizer.

For [test_ARAXRanker_test9_asset619](https://github.com/RTXteam/RTX/blob/0f9ec6364e8288aa9775acad302d9a2ab3ce9b81/code/ARAX/test/test_ARAX_ranker.py#L304) and [test_ARAXRanker_test9_asset623](https://github.com/RTXteam/RTX/blob/0f9ec6364e8288aa9775acad302d9a2ab3ce9b81/code/ARAX/test/test_ARAX_ranker.py#L360), I am not sure if they are due to the latest version of xDTD. But based on what I have checked on the old results.[ the target drug results](https://arax.ncats.io/?r=7fb53b61-161f-487a-82e3-1d704d3cc79e) don't contain any inferred edge from xDTD so I guess they might come from the `lookup` function. However, the failed tests don't find the target results in the returned list. I am wondering if it is due to the KG2.10.0 problem.

**Comment by dkoslicki** [comment]
Yes, @chunyuma that does seem to be sufficient. I wanted to be sure this didn't negatively affect the good work you've done with the ranker. And the other issues seem non-ranker, non-xDTD, so I'll approve the PR

**Review by dkoslicki — APPROVED** [review]

**Review by edeutsch — APPROVED** [review]

**Pull request merged**
