### PR TITLE
skip HGNC phenotype nodes #1170 #1169

### PR DESCRIPTION
**Pull request by kvarforl**
I tested this fix by adding  the debug output `print("skipping HGNC phenotype node", file=sys.stderr)` to L668 of `multi_ont_to_json_kg.py` and running the script `build-multi-ont-kg-1169.sh` on kg2steve.

This uses a the very small example .ttl file we created (`umls-hgnc-1169.ttl`) and a the test file `ont-load-inventory-1169.yaml`. The stderr log file, `~/test.log`, shows two nodes being skipped, as expected.

Something that confuses me that you might want to double check: when I test by using the full `umls-hgnc.ttl` file and the added debug statement, it did NOT appear in the log file. This is concerning, but I have no idea what the difference would be between the two, so ideas and feedback would be appreciated!

### CODE REVIEW

**Comment by saramsey** [comment]
Can you please paste the text of the toy TTL file in this issue?

**Comment by kvarforl** [comment]
yes! here it is
```
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix UMLS: <https://identifiers.org/umls:> .
@prefix UMLS_STY: <http://purl.bioontology.org/ontology/STY/> .


<http://purl.bioontology.org/ontology/HGNC/>
    a owl:Ontology ;
    rdfs:comment "RDF Version of the UMLS ontology HGNC; converted with the UMLS2RDF tool (https://github.com/ncbo/umls2rdf), developed by the NCBO project." ;
    rdfs:label "HGNC" ;
    owl:versionInfo "2020AA" ;
    UMLS:sver "2019_03" .

<http://purl.bioontology.org/ontology/HGNC/HGNC%3A355> a owl:Class ;
        skos:prefLabel """amelogenesis imperfecta 3, hypomaturation or hypoplastic type"""@en ;
        skos:notation """HGNC:355"""^^xsd:string ;
        skos:altLabel """AIH3"""@en , """AIH3 gene"""@en ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_CREATED> """1992-02-20"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_LAST_MODIFIED> """2011-02-24"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/GENESYMBOL> """AIH3"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_GROUP> """phenotype"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE> """phenotype only"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/PMID> """1358807"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/OMIM_ID> """301201"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENTREZGENE_ID> """201"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CYTOGENETIC_LOCATION> """Xq22-q28"""^^xsd:string ;
        UMLS:has_cui """C1412301"""^^xsd:string ;
        UMLS:has_tui """T028"""^^xsd:string ;
        UMLS:has_sty <http://purl.bioontology.org/ontology/STY/T028> ;
.

<http://purl.bioontology.org/ontology/HGNC/HGNC%3A13203> a owl:Class ;
        skos:prefLabel """activation induced cytidine deaminase"""@en ;
        skos:notation """HGNC:13203"""^^xsd:string ;
        skos:altLabel """AICDA"""@en , """AICDA gene"""@en , """AID"""@en , """ARP2"""@en , """CDA2"""@en , """HIGM2"""@en ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_CREATED> """2000-09-19"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DB_XR_ID> """Orphanet: 119554"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DB_XR_ID> """COSMIC: AICDA"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENSEMBLGENE_ID> """ENSG00000111732"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENTREZGENE_ID> """57379"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/GENESYMBOL> """AICDA"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_GROUP> """protein-coding gene"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE> """gene with protein product"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/MGD_ID> """MGI:1342279"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/OMIM_ID> """605257"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/REFSEQ_ID> """NM_020661"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/SWP> """Q9GZX7"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/VEGA_ID> """OTTHUMG00000168676"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CCDS_ID> """CCDS41747"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/RGD_ID> """RGD:1303222"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENA> """AB040430"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CYTOGENETIC_LOCATION> """12p13.31"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CCDS_ID> """CCDS81662"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/PREV_NAME> """activation-induced cytidine deaminase"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_NAME_CHANGED> """2016-07-04"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/MAPPED_UCSC_ID> """uc001qur.3"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_SPECIFIC_DB_XR> """AICDA base: Mutation registry for Aid deficiency&#x7C;http://structure.bmc.lu.se/idbase/AICDAbase/&#x7C;LRG_17&#x7C;http://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_17.xml"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_LAST_MODIFIED> """2018-12-24"""^^xsd:string ;
        UMLS:has_cui """C1421876"""^^xsd:string ;
        UMLS:has_tui """T028"""^^xsd:string ;
        UMLS:has_sty <http://purl.bioontology.org/ontology/STY/T028> ;
.

<http://purl.bioontology.org/ontology/HGNC/HGNC%3A8741> a owl:Class ;
        skos:prefLabel """polycystic ovary syndrome 1"""@en ;
        skos:notation """HGNC:8741"""^^xsd:string ;
        skos:altLabel """PCOS1"""@en , """PCOS1 gene"""@en ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_CREATED> """1996-07-19"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/GENESYMBOL> """PCOS1"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_GROUP> """phenotype"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE> """phenotype only"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/PMID> """16091490"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_LAST_MODIFIED> """2014-01-30"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/OMIM_ID> """184700"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CYTOGENETIC_LOCATION> """19p13.2"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENTREZGENE_ID> """5120"""^^xsd:string ;
        UMLS:has_cui """C1418386"""^^xsd:string ;
        UMLS:has_tui """T028"""^^xsd:string ;
        UMLS:has_sty <http://purl.bioontology.org/ontology/STY/T028> ;
 .

```

**Comment by saramsey** [comment]
Hmm, when I run this:
```
multi_ont_to_json_kg.py --test curies-to-categories.yaml curies-to-urls-map.yaml ont-load-inventory-pr1172.yaml pr1172.json
```
with the following config file `ont-load-inventory-pr1172.yaml`,
```
- # maps to CURIE prefix: biolink
  url: https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl.ttl
  file: biolink-model.owl.ttl
  download: true
  title: Biolink meta-model
-
  url:
  file: small.ttl
  download: false
  title: small test ttl file for PR 1172
```
I don't see any debug message. This is what is sent to the console:
```
https://raw.githubusercontent.com/biolink/biolink-model/master/biolink-model.owl.ttl
Reading ontology file: biolink-model.owl.ttl; size: 357.68 KiB
Reading ontology JSON file: biolink-model.owl.json; size: 632.44 KiB
file: biolink-model.owl.ttl; last modified: 2021-01-07 22:08:20 UTC
Reading ontology file: small.ttl; size: 5.91 KiB
Reading ontology JSON file: small.json; size: 9.07 KiB
file: small.ttl; last modified: 2021-01-07 21:37:40 UTC
Calling make_nodes_dict_from_ontologies_list
processing ontology: biolink_download_source:biolink-model.owl.ttl
processing ontology: HGNC:
Calling make_map_of_node_ontology_ids_to_curie_ids
Calling get_rels_dict
Number of edges: 792
Number of nodes: 699
Saving JSON file
```

**Comment by saramsey** [comment]
Ah, I see that I need to add debug code at L668. I have added this:
```
                                kg2_util.log_message(message="Skipping HGNC node because it has type \"phenotype only\" which is deprecated",
                                                     ontology_name=iri_of_ontology,
                                                     node_curie_id=node_curie_id,
                                                     output_stream=sys.stderr)
```
and now I get:
```
[http://purl.bioontology.org/ontology/HGNC/] Skipping HGNC node because it has type "phenotype only" which is deprecated: HGNC:8741
[http://purl.bioontology.org/ontology/HGNC/] Skipping HGNC node because it has type "phenotype only" which is deprecated: HGNC:355
```

**Comment by saramsey** [comment]
You get a gold star for indicating in the GitHub issue, the specific EC2 instance `kg2steve` on which you are working the issue. That is helpful.

**Comment by kvarforl** [comment]
okay that looks good and in line with what I got when running with the small ttl file. My only concern is that I didn't get similar output when running with the full ttl file. Is that the case for you as well?

**Comment by saramsey** [comment]
So, when I load `umls-hgnc.json` using ontobio, I do not see the `LOCUS_TYPE` basic property value:
```
>>> pprint.pprint(ont.node("http://purl.bioontology.org/ontology/HGNC/HGNC%3A355"))
{'id': 'http://purl.bioontology.org/ontology/HGNC/HGNC%3A355',
 'meta': {'basicPropertyValues': [{'pred': 'https://identifiers.org/umls:has_cui',
                                   'val': 'C1412301'},
                                  {'pred': 'http://www.w3.org/2004/02/skos/core#altLabel',
                                   'val': 'AIH3'},
                                  {'pred': 'http://www.w3.org/2004/02/skos/core#altLabel',
                                   'val': 'AIH3 gene'},
                                  {'pred': 'http://www.w3.org/2004/02/skos/core#prefLabel',
                                   'val': 'amelogenesis imperfecta 3, '
                                          'hypomaturation or hypoplastic type'},
                                  {'pred': 'https://identifiers.org/umls:has_tui',
                                   'val': 'T028'},
                                  {'pred': 'http://www.w3.org/2004/02/skos/core#notation',
                                   'val': 'HGNC:355'}]},
 'type': 'CLASS'}
```
even though the JSON file has it:
```
<http://purl.bioontology.org/ontology/HGNC/HGNC%3A355> a owl:Class ;
	skos:prefLabel """amelogenesis imperfecta 3, hypomaturation or hypoplastic type"""@en ;
	skos:notation """HGNC:355"""^^xsd:string ;
	skos:altLabel """AIH3"""@en , """AIH3 gene"""@en ;
	<http://purl.bioontology.org/ontology/HGNC/DATE_CREATED> """1992-02-20"""^^xsd:string ;
	<http://purl.bioontology.org/ontology/HGNC/DATE_LAST_MODIFIED> """2011-02-24"""^^xsd:string ;
	<http://purl.bioontology.org/ontology/HGNC/GENESYMBOL> """AIH3"""^^xsd:string ;
	<http://purl.bioontology.org/ontology/HGNC/LOCUS_GROUP> """phenotype"""^^xsd:string ;
	<http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE> """phenotype only"""^^xsd:string ;
	<http://purl.bioontology.org/ontology/HGNC/PMID> """1358807"""^^xsd:string ;
	<http://purl.bioontology.org/ontology/HGNC/OMIM_ID> """301201"""^^xsd:string ;
	<http://purl.bioontology.org/ontology/HGNC/ENTREZGENE_ID> """201"""^^xsd:string ;
	<http://purl.bioontology.org/ontology/HGNC/CYTOGENETIC_LOCATION> """Xq22-q28"""^^xsd:string ;
	UMLS:has_cui """C1412301"""^^xsd:string ;
	UMLS:has_tui """T028"""^^xsd:string ;
	UMLS:has_sty <http://purl.bioontology.org/ontology/STY/T028> ;
 .
```

**Comment by saramsey** [comment]
When I load the small TTL file, I see this:
```
>>> pprint.pprint(ont2.node("http://purl.bioontology.org/ontology/HGNC/HGNC%3A355"))
{'id': 'http://purl.bioontology.org/ontology/HGNC/HGNC%3A355',
 'meta': {'basicPropertyValues': [{'pred': 'http://purl.bioontology.org/ontology/HGNC/OMIM_ID',
                                   'val': '301201'},
                                  {'pred': 'http://purl.bioontology.org/ontology/HGNC/DATE_CREATED',
                                   'val': '1992-02-20'},
                                  {'pred': 'http://www.w3.org/2004/02/skos/core#prefLabel',
                                   'val': 'amelogenesis imperfecta 3, '
                                          'hypomaturation or hypoplastic type'},
                                  {'pred': 'https://identifiers.org/umls:has_sty',
                                   'val': 'http://purl.bioontology.org/ontology/STY/T028'},
                                  {'pred': 'http://purl.bioontology.org/ontology/HGNC/LOCUS_GROUP',
                                   'val': 'phenotype'},
                                  {'pred': 'http://www.w3.org/2004/02/skos/core#notation',
                                   'val': 'HGNC:355'},
                                  {'pred': 'http://www.w3.org/2004/02/skos/core#altLabel',
                                   'val': 'AIH3'},
                                  {'pred': 'http://purl.bioontology.org/ontology/HGNC/GENESYMBOL',
                                   'val': 'AIH3'},
                                  {'pred': 'http://purl.bioontology.org/ontology/HGNC/DATE_LAST_MODIFIED',
                                   'val': '2011-02-24'},
                                  {'pred': 'https://identifiers.org/umls:has_cui',
                                   'val': 'C1412301'},
                                  {'pred': 'http://purl.bioontology.org/ontology/HGNC/CYTOGENETIC_LOCATION',
                                   'val': 'Xq22-q28'},
                                  {'pred': 'https://identifiers.org/umls:has_tui',
                                   'val': 'T028'},
                                  {'pred': 'http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE',
                                   'val': 'phenotype only'},
                                  {'pred': 'http://www.w3.org/2004/02/skos/core#altLabel',
                                   'val': 'AIH3 gene'},
                                  {'pred': 'http://purl.bioontology.org/ontology/HGNC/ENTREZGENE_ID',
                                   'val': '201'},
                                  {'pred': 'http://purl.bioontology.org/ontology/HGNC/PMID',
                                   'val': '1358807'}]},
 'type': 'CLASS'}
```

**Comment by saramsey** [comment]
OK, I noticed that `umls-hgnc.ttl` has the following line of code toward the end of the file (at line 1084106):
```

<http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE> a owl:DatatypeProperty ;
	rdfs:label """Locus Type""";
	rdfs:comment """Locus Type""" .
```
When I add that line of code to the small TTL file, the `LOCUS_GROUP` property disappears. So now I have a small reproducible test TTL file:
```
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix UMLS: <https://identifiers.org/umls:> .
@prefix UMLS_STY: <http://purl.bioontology.org/ontology/STY/> .


<http://purl.bioontology.org/ontology/HGNC/>
    a owl:Ontology ;
    rdfs:comment "RDF Version of the UMLS ontology HGNC; converted with the UMLS2RDF tool (https://github.com/ncbo/umls2rdf), developed by the NCBO project." ;
    rdfs:label "HGNC" ;
    owl:versionInfo "2020AA" ;
    UMLS:sver "2019_03" .

<http://purl.bioontology.org/ontology/HGNC/HGNC%3A355> a owl:Class ;
        skos:prefLabel """amelogenesis imperfecta 3, hypomaturation or hypoplastic type"""@en ;
        skos:notation """HGNC:355"""^^xsd:string ;
        skos:altLabel """AIH3"""@en , """AIH3 gene"""@en ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_CREATED> """1992-02-20"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_LAST_MODIFIED> """2011-02-24"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/GENESYMBOL> """AIH3"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_GROUP> """phenotype"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE> """phenotype only"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/PMID> """1358807"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/OMIM_ID> """301201"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENTREZGENE_ID> """201"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CYTOGENETIC_LOCATION> """Xq22-q28"""^^xsd:string ;
        UMLS:has_cui """C1412301"""^^xsd:string ;
        UMLS:has_tui """T028"""^^xsd:string ;
        UMLS:has_sty <http://purl.bioontology.org/ontology/STY/T028> ;
.

<http://purl.bioontology.org/ontology/HGNC/HGNC%3A13203> a owl:Class ;
        skos:prefLabel """activation induced cytidine deaminase"""@en ;
        skos:notation """HGNC:13203"""^^xsd:string ;
        skos:altLabel """AICDA"""@en , """AICDA gene"""@en , """AID"""@en , """ARP2"""@en , """CDA2"""@en , """HIGM2"""@en ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_CREATED> """2000-09-19"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DB_XR_ID> """Orphanet: 119554"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DB_XR_ID> """COSMIC: AICDA"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENSEMBLGENE_ID> """ENSG00000111732"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENTREZGENE_ID> """57379"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/GENESYMBOL> """AICDA"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_GROUP> """protein-coding gene"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE> """gene with protein product"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/MGD_ID> """MGI:1342279"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/OMIM_ID> """605257"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/REFSEQ_ID> """NM_020661"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/SWP> """Q9GZX7"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/VEGA_ID> """OTTHUMG00000168676"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CCDS_ID> """CCDS41747"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/RGD_ID> """RGD:1303222"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENA> """AB040430"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CYTOGENETIC_LOCATION> """12p13.31"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CCDS_ID> """CCDS81662"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/PREV_NAME> """activation-induced cytidine deaminase"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_NAME_CHANGED> """2016-07-04"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/MAPPED_UCSC_ID> """uc001qur.3"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_SPECIFIC_DB_XR> """AICDA base: Mutation registry for Aid deficiency&#x7C;http://structure.bmc.lu.se/idbase/AICDAbase/&#x7C;LRG_17&#x7C;http://ftp.ebi.ac.uk/pub/databases/lrgex/LRG_17.xml"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_LAST_MODIFIED> """2018-12-24"""^^xsd:string ;
        UMLS:has_cui """C1421876"""^^xsd:string ;
        UMLS:has_tui """T028"""^^xsd:string ;
        UMLS:has_sty <http://purl.bioontology.org/ontology/STY/T028> ;
.

<http://purl.bioontology.org/ontology/HGNC/HGNC%3A8741> a owl:Class ;
        skos:prefLabel """polycystic ovary syndrome 1"""@en ;
        skos:notation """HGNC:8741"""^^xsd:string ;
        skos:altLabel """PCOS1"""@en , """PCOS1 gene"""@en ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_CREATED> """1996-07-19"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/GENESYMBOL> """PCOS1"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_GROUP> """phenotype"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE> """phenotype only"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/PMID> """16091490"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/DATE_LAST_MODIFIED> """2014-01-30"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/OMIM_ID> """184700"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/CYTOGENETIC_LOCATION> """19p13.2"""^^xsd:string ;
        <http://purl.bioontology.org/ontology/HGNC/ENTREZGENE_ID> """5120"""^^xsd:string ;
        UMLS:has_cui """C1418386"""^^xsd:string ;
        UMLS:has_tui """T028"""^^xsd:string ;
        UMLS:has_sty <http://purl.bioontology.org/ontology/STY/T028> ;
 .

<http://purl.bioontology.org/ontology/HGNC/LOCUS_GROUP> a owl:DatatypeProperty ;
	rdfs:label """Locus group""";
	rdfs:comment """Locus group""" .

<http://purl.bioontology.org/ontology/HGNC/LOCUS_TYPE> a owl:DatatypeProperty ;
	rdfs:label """Locus Type""";
	rdfs:comment """Locus Type""" .
```

**Comment by saramsey** [comment]
I think the issue is that the `LOCUS_TYPE` in the `umls-hgnc.ttl` file is an `owl:DatatypeProperty` and that is getting dropped in the conversion to OBO-Graph JSON format that is done by owltools. And if I instead convert the `umls-hgnc.ttl` file to OWL format using (for example) `robot` or `owltools`, I can see the `LOCUS_TYPE` properties and their values on the various HGNC nodes, but when I load the OWL file into `ontobio` I can't seem to access that property info. I've logged a question about this on the ontobio github page, here:

https://github.com/biolink/ontobio/issues/507

**Comment by saramsey** [comment]
OK, I think I can work around this issue, *but*.... it will likely require modifying our forked umls2rdf package

https://github.com/RTXteam/umls2rdf

(Specifically, I'll have to modify `umls2rdf.py`, line 446, in the `python3` branch). Then, we would need to redeploy umls2rdf to kg2steve, and rerun it (which would take a while). It would modify *every* umls-xxxxx.ttl file, by removing all the `owl:DatatypeProperty` statements.

**Comment by kvarforl** [comment]
Thank you so much for your sleuthing and documentation!

**Comment by saramsey** [comment]
I'll work on this in the morning. Sorry this has taken so long. It turned out to be... quite a puzzle.

**Comment by kvarforl** [comment]
That it did! thanks again for your help!

**Comment by saramsey** [comment]
Hi Lindsey, the Ontobio people are looking into it.  See bottom of thread here:

https://github.com/biolink/ontobio/issues/507

So, I think we should pause this PR until we have clarity from the Ontobio people about how to proceed. My reasoning is that, maybe there is a bug in owltools or ontobio that is preventing us from "seeing" the `LOCUS_TYPE` owl:DatatypeProperty for phenotype HGNC nodes, using ontobio. And if that is the case, certainly, the appropriate fix is to fix the bug in the tooling. On the other hand, if it turns out that there is truly no way to access owl:DatatypeProperty information in ontobio, then we may be forced to modify `umls2rdf` in order to flip these properties to object properties; but I would rather not have to do that unless there is no other option, as it will affect a *lot* of TTL files and there could be unintended consequences.

**Comment by kvarforl** [comment]
Should I wait to start the KG2.5.0 build for this to be merged in, or go ahead without it?

**Comment by dkoslicki** [comment]
@saramsey Is this still relevant? Should we delete or merge?

**Comment by edeutsch** [comment]
All relevant code has since been rewritten by @ecwood so this PR is no longer relevant. Closing this PR.

**Pull request closed without merging**
