### PR TITLE
#1708

### PR DESCRIPTION
**Pull request by saramsey**
This should fix the issue that we are having (#1708) with the ARAX service dying when the client terminates early. Technically, the extensive edits that I put in `ARAX_query.py` are not required for this PR to work (only the slight changes to `__main__.py` are required) but I think my changes to `ARAX_query.py` have improved its thread-safety and we should probably review them for possible inclusion in this PR.

### CODE REVIEW

**Comment by saramsey** [comment]
The issue was when the client disconnects, it causes a `SIGPIPE` signal and apparently, the signal handler that I had installed in `__main__.py` basically silently terminates cpython with absolutely no opportunity to prevent the termination. Changing to a custom signal handler that prints to `stderr` (but otherwise does nothing) seems to fix the issue.

**Comment by saramsey** [comment]
The commit is showing up in GitHub as coming from @edeutsch, probably due to the git global config for Linux user `rt` on `arax-backup.rtx.ai`; sorry for any confusion.

**Comment by saramsey** [comment]
Please note, the thread-locking code in `ARAX_query.py` in the `issue-1708` branch is incomplete. I believe it is not enough for the response message-streaming thread to use locking; the thread that puts messages in the response must also use locking, to be fully thread-safe. Arranging that will take some time, and probably some modifications to the response class. At this point I am thinking that a custom subclass of response is probably the best way to accomplish the locking.

**Comment by saramsey** [comment]
OK, with commit ec48c604, I am attempting to add locking within the thread that is adding messages to the response. I did this by subclassing `ARAX_response` with a class, `response_locking`, that adds thread locking around the `__add_message` method call. It seems to work (for both streaming and non-streaming), though I am not sure if it breaks any of the built-in pytest tests. Anyhow, we should carefully review these changes in a code review to make sure they are reasonable. With the most recent commit, I have removed some locking (in the "streamer" thread) that I deemed no longer necessary after a more careful review of the code.

**Review by edeutsch — APPROVED** [review]
Thanks for figuring this out and fixing it, Steve! All the changes seem reasonable to me. thanks!

**Comment by saramsey** [comment]
> Thanks for figuring this out and fixing it, Steve! All the changes seem reasonable to me. thanks!

I appreciate your reviewing the code, thank you. @finnagin has kindly agreed to do some testing on `arax-backup.rtx.ai`.

**Comment by saramsey** [comment]
Commit b77ba01 is to remove some thread-locking code that I realized is no longer needed. It should simplify `ARAX_query.py` a bit.

**Review by finnagin — APPROVED** [review]
Passed the tests on arax-backup when both the production and kg2 endpoints were using the issue-1708 branch so I think this is probably good to merge.

**Comment by saramsey** [comment]
Thank you @finnagin

**Comment by saramsey** [comment]
Woo hoo!

**Pull request merged**
