### PR TITLE
Merging Dan's Benchmark code into master

### PR DESCRIPTION
**Pull request by power10dan**
This branch contains my testing harness for the Google Distance Function.

### CODE REVIEW

**Comment by saramsey** [comment]
@power10dan , can you please move the code to code/reasoningtool/google_dist_benchmark?

Thank you,
Steve

**Comment by saramsey** [comment]
I'll let @dkoslicki be in charge of vetting and accepting the PR

**Comment by dkoslicki** [comment]
@power10dan as @saramsey mentioned, the directory should be moved to a different location. I think the best place is code/reasoningtool/QuestionAnswering/google_dist_benchmark as this is Reasoning (or QuestionAnswering) code.

Furthermore, I'm going to suggest work along these NGD investigations be done in separate branch (as you have been doing), and then merged only once we've identified a feasible way to speed up the NGD function (via the ways we've been discussing). That way the master branch is only updated after a working and efficient solution is found.

**Comment by power10dan** [comment]
Got it @dkoslicki  and @saramsey . I shall reject this pull request myself and only file a PR once we got a feasible solution moving forward with the NGD optimization.

**Comment by power10dan** [comment]
Actually, I can't reject the PR myself 👎  
@dkoslicki , can you reject this PR for me?

**Pull request closed without merging**
